plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sjllsjlp.mqccy'
    compileSdk 33

    defaultConfig {
        applicationId "com.sjllsjlp.wmccl"
        minSdk 24
        targetSdk 33
        versionCode 3
        versionName "1.0.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'armeabi-v7a','x86','arm64-v8a','x86_64','armeabi'
        }

        packagingOptions {
            doNotStrip "*/armeabi-v7a/*.so"
            doNotStrip "*/x86/*.so"
            doNotStrip "*/arm64-v8a/*.so"
            doNotStrip "*/x86_64/*.so"
            doNotStrip "armeabi.so"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
//    implementation 'com.qq.e.union:union:+' // 普通版本


    implementation files('libs/oaid_sdk_2.3.0.aar')
    //AndroidX
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    // AndroidX依赖和上面Supprot库依赖，二选一
    implementation "androidx.appcompat:appcompat:$version"
    implementation "androidx.recyclerview:recyclerview:$version"

    implementation fileTree(include: ['*.jar','*.aar'], dir: 'libs')
    //腾讯优量汇
    implementation fileTree(include: ["*.jar","*.aar"], dir: 'libs/AdNetworks/gdt')
    //穿山甲
    implementation fileTree(include: ["*.jar","*.aar"], dir: 'libs/AdNetworks/csj')
    //Gromore
    implementation fileTree(include: ["*.jar","*.aar"], dir: 'libs/AdNetworks/gromore')
    // 百度SDK aar包，请将提供的aar包拷⻉到libs⽬录下，添加依赖。根据接⼊版本修改SDK包名
    implementation fileTree(include: ["*.jar", "*.aar"], dir: 'libs/AdNetworks/baidu')

    //TapTap
//    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs/AdNetworks/taptap')
    implementation "com.github.bumptech.glide:glide:4.9.0"
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.0.1'
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
    implementation "com.android.support:support-annotations:28.0.0"

}